"""LLM segmenter tests — exercises segment_input_by_actions without
hitting ollama. Feeds it the action lists Gemma would return and verifies
the resulting op tuples preserve text exactly."""
from __future__ import annotations
import pytest

import korder.actions  # noqa: F401  (default registrations)
from korder.actions.codes import (
    KEY_BACKSPACE,
    KEY_ENTER,
    KEY_LCTRL,
)
from korder.intent import segment_input_by_actions


def test_no_actions_returns_text_only():
    ops = segment_input_by_actions("hello world", [])
    assert ops == [("text", "hello world")]


def test_no_actions_preserves_trailing_whitespace():
    """The caller appends ' ' for inter-commit separation; must survive."""
    ops = segment_input_by_actions("Dawno, dawno temu ", [])
    assert ops == [("text", "Dawno, dawno temu ")]


def test_no_actions_preserves_polish_diacritics():
    """Regression: text used to round-trip through the LLM and got mangled."""
    text = "Myślę, że to jest OK."
    ops = segment_input_by_actions(text, [])
    # Period stripped via outer rstrip? No — outer edges are preserved.
    assert ops == [("text", text)]


def test_action_only():
    ops = segment_input_by_actions(
        "Naciśnij Enter.",
        [{"phrase": "Naciśnij Enter", "name": "press_enter"}],
    )
    assert ops == [("key", KEY_ENTER)]


def test_text_before_action_preserves_diacritics():
    """The bug we fixed: text segments come from the original input
    verbatim, not regenerated by the LLM."""
    ops = segment_input_by_actions(
        "Co tu się stało? Naciśnij Enter.",
        [{"phrase": "Naciśnij Enter", "name": "press_enter"}],
    )
    assert ops == [("text", "Co tu się stało"), ("key", KEY_ENTER)]


def test_action_then_text_preserves_trailing_whitespace_after_action():
    ops = segment_input_by_actions(
        "press enter and run it ",
        [{"phrase": "press enter", "name": "press_enter"}],
    )
    assert ops == [("key", KEY_ENTER), ("text", "and run it ")]


def test_unknown_action_name_returns_none():
    """Signals fallback to regex parser."""
    ops = segment_input_by_actions(
        "do something",
        [{"phrase": "do something", "name": "nonexistent_action"}],
    )
    assert ops is None


def test_phrase_not_found_in_input_returns_none():
    """LLM hallucinated a phrase; we catch it and fall back."""
    ops = segment_input_by_actions(
        "hello world",
        [{"phrase": "press enter", "name": "press_enter"}],
    )
    assert ops is None


def test_legacy_type_value_shape_still_works():
    """Old prompts emitted {type: key, value: enter}; backward compat."""
    ops = segment_input_by_actions(
        "Naciśnij Enter",
        [{"phrase": "Naciśnij Enter", "type": "key", "value": "enter"}],
    )
    assert ops == [("key", KEY_ENTER)]


def test_legacy_shortcut_value_is_action_name():
    ops = segment_input_by_actions(
        "Usuń słowo",
        [{"phrase": "Usuń słowo", "type": "shortcut", "value": "delete_word"}],
    )
    assert ops == [("combo", [KEY_LCTRL, KEY_BACKSPACE])]


def test_actions_must_be_a_list():
    assert segment_input_by_actions("hi", "not a list") is None


def test_empty_phrase_skipped():
    """Empty phrase entries are ignored, not treated as a fail."""
    ops = segment_input_by_actions(
        "hello",
        [{"phrase": "", "name": "press_enter"}],
    )
    assert ops == [("text", "hello")]


def test_multiple_actions_in_order():
    ops = segment_input_by_actions(
        "first press tab second press enter third",
        [
            {"phrase": "press tab", "name": "press_tab"},
            {"phrase": "press enter", "name": "press_enter"},
        ],
    )
    assert ops == [
        ("text", "first"),
        ("key", 15),  # KEY_TAB
        ("text", "second"),
        ("key", KEY_ENTER),
        ("text", "third"),
    ]


@pytest.mark.parametrize("text", [
    "Dawno, dawno temu za daleką krainą",
    "Co tu się stało?",
    "Myślę, że to jest OK.",
    "obróć okno o 20 stopni",
    "zwiększ rozmiar fontu",
])
def test_polish_text_unchanged_when_no_actions(text):
    """Battery of phrases that previously got mangled when LLM regenerated text."""
    ops = segment_input_by_actions(text, [])
    assert ops == [("text", text)]


def test_parameterized_action_passes_params_to_factory():
    """Spotify search action wraps the search in a callable that the
    inject backend dispatches at execution time."""
    ops = segment_input_by_actions(
        "Zagraj na Spotify Despacito",
        [{
            "phrase": "Zagraj na Spotify Despacito",
            "name": "spotify_play",
            "params": {"query": "Despacito"},
        }],
    )
    assert ops is not None
    assert len(ops) == 1
    kind, fn = ops[0]
    assert kind == "callable"
    assert callable(fn)


def test_parameterized_action_with_empty_params_returns_pending():
    """When LLM identifies the action but provides no params, segmenter
    should emit a pending_action marker rather than executing with empty
    query. MainWindow then waits for the next commit as the parameter."""
    ops = segment_input_by_actions(
        "Odtwórz w Spotify",
        [{"phrase": "Odtwórz w Spotify", "name": "spotify_play"}],
    )
    assert ops is not None
    assert ("pending_action", "spotify_play") in ops
